### ISSUE TITLE
An error when running the linear example

### ISSUE THREAD

**Issue by kanglcn** [AlTarFramework/altar#31]
Hello.
I clone and install the recent developing pyre and altar.
When I try to run the linear example, just enter the directory `alter/models/linear/examples` and run `linear` in the terminal,
I get
```altar: step
  β: 0
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.052000000000000005
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.110776
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.171243232
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.23837253020799998
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.32215155188512
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.4278959097910413
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.5629124750803556
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.7377474850482133
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 0.9737747485048214
  θ: (4096 samples) x (18 parameters)
altar: step
  β: 1.0
  θ: (4096 samples) x (18 parameters)
altar: node 'wid:05' is unresolved
```
And I don't know how to fix it.

**Comment by lijun99** [comment]
Currently not all things are put together for a public release yet. If you want to try a development version of altar, I suggest you to pull from 

https://github.com/lijun99/pyre.git
https://github.com/lijun99/altar.git

then follow the documentation to run your models.

**Comment by kanglcn** [comment]
After I compile `pyre` from your repository, when I try
`python3 -c 'import cuda'`
I got
``` 
>> /home/kanglcn/.local/pyre/packages/cuda/__init__.py:19: error(cuda): in '<module>':
 -- could not find 'cuda' support
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kanglcn/.local/pyre/packages/cuda/__init__.py", line 12, in <module>
    from . import cuda
ImportError: /home/kanglcn/.local/pyre/packages/cuda/cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: cudaStreamDestroy
```
even through the compiling is perfect.

**Comment by lijun99** [comment]
Have you tried the CPU code? 

To trace your GPU problem, I will need more details, 
1) do you have a physical nvidia graphical card, what is the model?
2) what version of the CUDA toolkit do you have?
3) have you added the CUDA libraries to LD_LIBRARY_PATH?
4) other system info, like Linux version, GNU compiler version

BTW, it is always a good practice to provide more details when you submit a question.

**Comment by lijun99** [comment]
I can repeat your problem: for some newer systems, the cudart library needs to be explicitly linked. I have updated https://github.com/lijun99/pyre.git. Please pull and try again.

**Comment by kanglcn** [comment]
```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Quadro K620"
  CUDA Driver Version / Runtime Version          11.1 / 11.2
  CUDA Capability Major/Minor version number:    5.0
  Total amount of global memory:                 1980 MBytes (2075852800 bytes)
  ( 3) Multiprocessors, (128) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            1124 MHz (1.12 GHz)
  Memory Clock rate:                             900 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        65536 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.1, CUDA Runtime Version = 11.2, NumDevs = 1
Result = PASS
```
Sorry for that I didn't provide sufficient messages. Here are some informations from the cuda `deviceQuery`'s result.

And result from `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K620         Off  | 00000000:01:00.0  On |                  N/A |
| 40%   53C    P0     4W /  30W |    765MiB /  1979MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
My linux kernel is 5.10.2-2-MANJARO and gcc version is 10.2.0

I have pull the latest code and this time `import cuda` successfully.

Then I try to run the code in the tests directory. I try several scripts and they all run without any error expect the `bcast.py` in the `cuda` directory. I get
```
/home/kanglcn/software/pyre/lib/cuda/elementwise.cu(49) : CUDA error : cuda error: cudalib::elementwise::set_value : (209) no kernel image is available for execution on the device.
```
I doubt this is because my GPU is old. And the CUDA and GPU driver are the newest distribution from manjaro's official repositories. I have got similar error when I try the lastest Pytorch. That is because Pytorch don't support GPU with compute capacity less than 7.5.

**Comment by lijun99** [comment]
CUDA 11 uses sm_52 as default.You will need to add -DCMAKE_CUDA_FLAGS="-arch=sm_50" to cmake, and actually, for all your other cuda applications. Your card doesn't have double precision computing power, but SP should work fine.
