### ISSUE TITLE
error running Mogi example synthetic code

### ISSUE THREAD

**Issue by EJFielding** [AlTarFramework/altar#6]
I get an error when I try to run the synthetic example code for the Mogi model.
`mogi/examples/synthetic]` fielding% python3 mogi.py
Traceback (most recent call last):
  File "mogi.py", line 18, in <module>
    import altar.models.mogi
  File "/Users/fielding/Documents/progs/Caltech/AlTar-2.0/models/mogi/mogi/__init__.py", line 15, in <module>
    from .ext import libmogi
  File "/Users/fielding/Documents/progs/Caltech/AlTar-2.0/models/mogi/mogi/ext/__init__.py", line 13, in <module>
    from . import mogi as libmogi
ImportError: cannot import name 'mogi'`

**Comment by EJFielding** [comment]
The synthetic generation program now works for me with no errors.
